------------------------------------------------------------
-- TABELA: usuarios  (entity: Usuario)
------------------------------------------------------------
CREATE TABLE usuarios (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE
);

------------------------------------------------------------
-- TABELA: skills  (entity: Skill)
------------------------------------------------------------
CREATE TABLE skills (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      VARCHAR(120) NOT NULL,
  descricao VARCHAR(400)
);

------------------------------------------------------------
-- TABELA: courses  (entity: Course)
------------------------------------------------------------
CREATE TABLE courses (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title    VARCHAR(200) NOT NULL,
  provider VARCHAR(120),
  url      VARCHAR(400)
);

------------------------------------------------------------
-- TABELA: learning_paths  (entity: LearningPath)
------------------------------------------------------------
CREATE TABLE learning_paths (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);

------------------------------------------------------------
-- TABELA: learningpath_courses (join @ManyToMany)
-- @JoinTable(name = "learningpath_courses",
--   joinColumns = @JoinColumn(name = "learningpath_id"),
--   inverseJoinColumns = @JoinColumn(name = "course_id"))
------------------------------------------------------------
CREATE TABLE learningpath_courses (
  learningpath_id BIGINT NOT NULL,
  course_id       BIGINT NOT NULL,
  CONSTRAINT pk_learningpath_courses PRIMARY KEY (learningpath_id, course_id),
  CONSTRAINT fk_lc_learningpath FOREIGN KEY (learningpath_id) REFERENCES learning_paths(id),
  CONSTRAINT fk_lc_course       FOREIGN KEY (course_id)       REFERENCES courses(id)
);

------------------------------------------------------------
-- TABELA: user_skills  (entity: UserSkill)
-- @ManyToOne Usuario -> coluna usuario_id
-- @ManyToOne Skill   -> coluna skill_id
------------------------------------------------------------
CREATE TABLE user_skills (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  skill_id   BIGINT NOT NULL,
  level      INT,
  CONSTRAINT fk_us_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
  CONSTRAINT fk_us_skill   FOREIGN KEY (skill_id)   REFERENCES skills(id)
);

------------------------------------------------------------
-- TABELA: recommendations  (entity: Recommendation)
------------------------------------------------------------
CREATE TABLE recommendations (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content VARCHAR(2000)
);

------------------------------------------------------------
-- TABELA: works  (entity: Work)
------------------------------------------------------------
CREATE TABLE works (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  description VARCHAR(1000)
);
